networks:
    users:

volumes:
    mysql-data:

services:

    nginx:
        image: nginx:stable-alpine
        container_name: users_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - php
        networks:
            - users

    php:
        build:
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
            context: .
            dockerfile: ./.docker/php/Dockerfile
        container_name: users_app
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - users

    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: users_db
        restart: unless-stopped
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - users

    db-test:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: users_db_test
        restart: unless-stopped
        ports:
            - "33071:3307"
        expose:
            - 3307
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: users_test
            MYSQL_PASSWORD: 1234
            MYSQL_TCP_PORT: 3307
        networks:
            - users


